const GOLD = "#C4975A";
const BG = "#070809";

export default function TermsOfService() {
  return (
    <div style={{ background: BG, minHeight: "100vh", color: "#fff", fontFamily: "Arial, sans-serif" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&family=DM+Sans:wght@300;400;500&display=swap');
        *,*::before,*::after{box-sizing:border-box;margin:0;padding:0;}
      `}</style>

      <nav style={{ padding: "16px 24px", borderBottom: "1px solid rgba(255,255,255,.05)", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <a href="/" style={{ fontFamily: "'Playfair Display',serif", color: GOLD, fontSize: "16px", fontWeight: "700", textDecoration: "none" }}>BrandMind</a>
        <a href="/" style={{ color: "#555", fontSize: "13px", textDecoration: "none" }}>← Back to Home</a>
      </nav>

      <div style={{ maxWidth: "720px", margin: "0 auto", padding: "60px 24px 100px" }}>
        <p style={{ color: GOLD, fontSize: "10px", letterSpacing: ".22em", fontWeight: "700", marginBottom: "12px" }}>LEGAL</p>
        <h1 style={{ fontFamily: "'Playfair Display',serif", fontSize: "clamp(32px,5vw,52px)", color: "#EDE5D4", marginBottom: "12px" }}>Terms of Service</h1>
        <p style={{ color: "#444", fontSize: "13px", marginBottom: "48px" }}>Effective: May 2026</p>

        <div style={{ display: "flex", flexDirection: "column", gap: "36px" }}>

          <section>
            <h2 style={{ color: "#EDE5D4", fontSize: "18px", fontWeight: "600", marginBottom: "12px" }}>Agreement</h2>
            <p style={{ color: "#777", fontSize: "14px", lineHeight: "1.85" }}>
              By accessing or using BrandMind, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform. These terms apply to all users, whether free or paying.
            </p>
          </section>

          <section>
            <h2 style={{ color: "#EDE5D4", fontSize: "18px", fontWeight: "600", marginBottom: "12px" }}>What BrandMind Provides</h2>
            <p style={{ color: "#777", fontSize: "14px", lineHeight: "1.85", marginBottom: "12px" }}>BrandMind is an AI-powered platform that generates:</p>
            <ul style={{ color: "#777", fontSize: "14px", lineHeight: "2.1", paddingLeft: "20px" }}>
              <li>Brand identity kits (logo concepts, color palettes, typography, taglines)</li>
              <li>Instagram post captions and hooks</li>
              <li>Website copywriting (hero, about, services sections)</li>
              <li>Reel scripts</li>
              <li>Social media bios</li>
            </ul>
            <p style={{ color: "#777", fontSize: "14px", lineHeight: "1.85", marginTop: "12px" }}>
              All content is generated by artificial intelligence based on the inputs you provide. Results are unique per generation but are not guaranteed to be exclusive, trademarked, or legally protected.
            </p>
          </section>

          <section>
            <h2 style={{ color: "#EDE5D4", fontSize: "18px", fontWeight: "600", marginBottom: "12px" }}>Payment & Access</h2>
            <ul style={{ color: "#777", fontSize: "14px", lineHeight: "2.1", paddingLeft: "20px" }}>
              <li>The Pro plan is a <span style={{ color: GOLD }}>one-time payment of $49</span> — no subscriptions, no recurring charges.</li>
              <li>Payment is processed securely by Stripe.</li>
              <li>Access is granted immediately upon successful payment confirmation.</li>
              <li>You may use the platform from any device by signing in with the email used at purchase.</li>
            </ul>
          </section>

          <section>
            <h2 style={{ color: "#EDE5D4", fontSize: "18px", fontWeight: "600", marginBottom: "12px" }}>AI-Generated Content Disclaimer</h2>
            <p style={{ color: "#777", fontSize: "14px", lineHeight: "1.85", marginBottom: "12px" }}>
              All output from BrandMind is generated by AI and provided as a creative starting point. By using the platform, you acknowledge:
            </p>
            <ul style={{ color: "#777", fontSize: "14px", lineHeight: "2.1", paddingLeft: "20px" }}>
              <li>AI-generated content may not be unique, original, or free of unintentional similarities to existing brands.</li>
              <li>You are solely responsible for verifying that your chosen brand name, logo concepts, and content do not infringe on existing trademarks or copyrights.</li>
              <li>BrandMind does not guarantee that generated content is legally safe for commercial use without your own due diligence.</li>
              <li>We recommend consulting a legal professional before registering trademarks or using generated content commercially at scale.</li>
            </ul>
          </section>

          <section>
            <h2 style={{ color: "#EDE5D4", fontSize: "18px", fontWeight: "600", marginBottom: "12px" }}>Ownership of Generated Content</h2>
            <p style={{ color: "#777", fontSize: "14px", lineHeight: "1.85" }}>
              You retain ownership of the brand inputs you provide and the generated outputs you receive. BrandMind does not claim ownership over your generated brand kits. We may use anonymized, non-identifiable examples for marketing purposes unless you opt out by contacting us.
            </p>
          </section>

          <section>
            <h2 style={{ color: "#EDE5D4", fontSize: "18px", fontWeight: "600", marginBottom: "12px" }}>Prohibited Uses</h2>
            <p style={{ color: "#777", fontSize: "14px", lineHeight: "1.85", marginBottom: "12px" }}>You may not use BrandMind to:</p>
            <ul style={{ color: "#777", fontSize: "14px", lineHeight: "2.1", paddingLeft: "20px" }}>
              <li>Generate content that is illegal, harmful, threatening, or discriminatory.</li>
              <li>Attempt to reverse-engineer, scrape, or exploit the platform's AI systems.</li>
              <li>Share, resell, or sublicense your account access to others.</li>
              <li>Use the platform in a way that violates any applicable law or regulation.</li>
            </ul>
          </section>

          <section>
            <h2 style={{ color: "#EDE5D4", fontSize: "18px", fontWeight: "600", marginBottom: "12px" }}>Limitation of Liability</h2>
            <p style={{ color: "#777", fontSize: "14px", lineHeight: "1.85" }}>
              BrandMind is provided "as is" without warranties of any kind, express or implied. We are not liable for any indirect, incidental, or consequential damages arising from your use of the platform, including but not limited to loss of revenue, data, or business opportunities. Our maximum liability to you shall not exceed the amount you paid for the service ($49).
            </p>
          </section>

          <section>
            <h2 style={{ color: "#EDE5D4", fontSize: "18px", fontWeight: "600", marginBottom: "12px" }}>Termination</h2>
            <p style={{ color: "#777", fontSize: "14px", lineHeight: "1.85" }}>
              We reserve the right to suspend or terminate access to BrandMind if these Terms are violated, without refund. You may stop using the platform at any time.
            </p>
          </section>

          <section>
            <h2 style={{ color: "#EDE5D4", fontSize: "18px", fontWeight: "600", marginBottom: "12px" }}>Changes to These Terms</h2>
            <p style={{ color: "#777", fontSize: "14px", lineHeight: "1.85" }}>
              We may update these Terms occasionally. Continued use of BrandMind after changes are posted constitutes acceptance. We will notify registered users of material changes via email.
            </p>
          </section>

          <section>
            <h2 style={{ color: "#EDE5D4", fontSize: "18px", fontWeight: "600", marginBottom: "12px" }}>Contact</h2>
            <p style={{ color: "#777", fontSize: "14px", lineHeight: "1.85" }}>
              Questions about these Terms? Email <a href="mailto:juanalvarados2012@gmail.com" style={{ color: GOLD, textDecoration: "none" }}>juanalvarados2012@gmail.com</a>
            </p>
          </section>

        </div>
      </div>

      <footer style={{ borderTop: "1px solid rgba(255,255,255,.04)", padding: "20px 24px", textAlign: "center" }}>
        <div style={{ display: "flex", gap: "20px", justifyContent: "center", flexWrap: "wrap" }}>
          <a href="/privacy" style={{ color: "#444", fontSize: "11px", textDecoration: "none" }}>Privacy Policy</a>
          <a href="/terms" style={{ color: GOLD, fontSize: "11px", textDecoration: "none" }}>Terms of Service</a>
          <a href="/refund" style={{ color: "#444", fontSize: "11px", textDecoration: "none" }}>Refund Policy</a>
        </div>
      </footer>
    </div>
  );
}
